/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 966ac163-ac51-44b3-a16c-1355fb2e57e5
-/

/-
We define the property `is_valid_S` for a set of positive integers $S$.
We prove that any such set $S$ must contain all positive integers.
The proof proceeds by strong induction. First, we show $1 \in S$.
Then for any $n > 1$, we show there exists $k < n$ such that $n \mid 2025^k - 15^k$.
Since $k < n$, $k \in S$ by the inductive hypothesis.
The property of $S$ implies that all divisors of $2025^k - 15^k$ are in $S$, so $n \in S$.
The existence of such $k$ is guaranteed by analyzing the prime factorization of $n$ and the order of 135 modulo the coprime part of $n$.
-/

import Mathlib

open scoped Classical

set_option maxHeartbeats 0

noncomputable section

/-
Definition of the property of set S.
-/
def is_valid_S (S : Set ℕ) : Prop :=
  S.Nonempty ∧ (∀ n ∈ S, n > 0) ∧
  ∀ n ∈ S, ∀ d : ℕ, d ∣ 2025^n - 15^n → d ∈ S

/-
1 is in S.
-/
theorem one_in_S (S : Set ℕ) (h : is_valid_S S) : 1 ∈ S := by
  obtain ⟨ n, hn ⟩ := h.1;
  have := h.2.2 n hn 1 ( by norm_num );
  assumption

/-
For any n > 1, there exists k < n such that n divides 2025^k - 15^k.
-/
lemma exists_divisor_exponent (n : ℕ) (hn : n > 1) : ∃ k, 0 < k ∧ k < n ∧ n ∣ 2025^k - 15^k := by
  -- Let $n=3^a 5^b m$, where $a, b$ are non-negative integers, $\gcd(m, 15)=1$.
  obtain ⟨a, b, m, ha, hb, hm⟩ : ∃ a b m, n = 3^a * 5^b * m ∧ a ≥ 0 ∧ b ≥ 0 ∧ Nat.gcd m 15 = 1 := by
    -- Let $a$ be such that $3^a \mid n$ and $3^{a+1} \nmid n$, and similarly let $b$ be such that $5^b \mid n$ and $5^{b+1} \nmid n$.
    obtain ⟨a, ha⟩ : ∃ a, 3^a ∣ n ∧ ¬3^(a+1) ∣ n := by
      exact ⟨ Nat.factorization n 3, Nat.ordProj_dvd _ _, Nat.pow_succ_factorization_not_dvd hn.ne_bot ( by decide ) ⟩
    obtain ⟨b, hb⟩ : ∃ b, 5^b ∣ n ∧ ¬5^(b+1) ∣ n := by
      exact ⟨ Nat.factorization n 5, Nat.ordProj_dvd _ _, Nat.pow_succ_factorization_not_dvd hn.ne_bot ( by decide ) ⟩;
    -- Let $m$ be such that $n = 3^a * 5^b * m$.
    obtain ⟨m, hm⟩ : ∃ m, n = 3^a * 5^b * m := by
      exact Nat.Coprime.mul_dvd_of_dvd_of_dvd ( by apply Nat.Coprime.pow ; norm_num ) ha.1 hb.1;
    simp +zetaDelta at *;
    exact ⟨ a, b, m, hm, Nat.Coprime.symm <| Nat.Coprime.mul_left ( Nat.Prime.coprime_iff_not_dvd ( by norm_num ) |>.2 fun h => ha.2 <| hm.symm ▸ mul_dvd_mul ( dvd_mul_right _ _ ) h ) ( Nat.Prime.coprime_iff_not_dvd ( by norm_num ) |>.2 fun h => hb.2 <| hm.symm ▸ mul_dvd_mul ( dvd_mul_left _ _ ) h ) ⟩;
  by_cases hm_eq_one : m = 1;
  · use a + b + 1;
    aesop;
    · rcases a with ( _ | a ) <;> rcases b with ( _ | b ) <;> norm_num [ Nat.pow_succ', Nat.mul_assoc ] at *;
      · exact Nat.recOn b ( by norm_num ) fun n ihn => by norm_num [ Nat.pow_succ' ] at * ; linarith;
      · exact Nat.recOn a ( by norm_num ) fun n ihn => by norm_num [ Nat.pow_succ' ] at * ; linarith;
      · nlinarith [ show 3 ^ a ≥ a + 1 by exact Nat.recOn a ( by norm_num ) fun n ihn => by rw [ pow_succ' ] ; linarith [ ihn, pow_pos ( show 0 < 3 by norm_num ) n ], show 5 ^ b ≥ b + 1 by exact Nat.recOn b ( by norm_num ) fun n ihn => by rw [ pow_succ' ] ; linarith [ ihn, pow_pos ( show 0 < 5 by norm_num ) n ] ];
    · refine Nat.dvd_sub' ?_ ?_;
      · rw [ show 2025 = 3 ^ 4 * 5 ^ 2 by norm_num, mul_pow ];
        exact mul_dvd_mul ( dvd_trans ( pow_dvd_pow _ ( by linarith ) ) ( pow_dvd_pow_of_dvd ( by decide ) _ ) ) ( dvd_trans ( pow_dvd_pow _ ( by linarith ) ) ( pow_dvd_pow_of_dvd ( by decide ) _ ) );
      · exact dvd_trans ( mul_dvd_mul ( pow_dvd_pow _ ( Nat.le_succ_of_le ( Nat.le_add_right _ _ ) ) ) ( pow_dvd_pow _ ( Nat.le_succ_of_le ( Nat.le_add_left _ _ ) ) ) ) ( by rw [ ← mul_pow ] ; exact pow_dvd_pow _ ( Nat.le_refl _ ) );
  · -- Let $k_0 = \text{ord}_m(135)$. Since $\gcd(m, 135) = 1$, this order exists and $k_0 \mid \phi(m) < m$ (if $m > 1$).
    obtain ⟨k0, hk0⟩ : ∃ k0, 0 < k0 ∧ k0 < m ∧ 135^k0 ≡ 1 [MOD m] := by
      -- Since $\gcd(m, 15) = 1$, we know that $135$ and $m$ are coprime.
      have h_coprime : Nat.gcd 135 m = 1 := by
        rw [ Nat.gcd_comm ] at hm ⊢; aesop;
        exact Nat.Coprime.symm ( Nat.Coprime.mul_left ( show Nat.Coprime 3 m from Nat.prime_three.coprime_iff_not_dvd.mpr fun h₃ => by have := Nat.dvd_gcd ( by decide : 3 ∣ 15 ) h₃; simp_all +decide ) ( show Nat.Coprime 45 m from Nat.Coprime.mul_left ( show Nat.Coprime 3 m from Nat.prime_three.coprime_iff_not_dvd.mpr fun h₃ => by have := Nat.dvd_gcd ( by decide : 3 ∣ 15 ) h₃; simp_all +decide ) ( show Nat.Coprime 15 m from hm ) ) );
      have h_order : ∃ k0, 0 < k0 ∧ k0 < m ∧ 135^k0 ≡ 1 [MOD m] := by
        have h_euler : 135 ^ Nat.totient m ≡ 1 [MOD m] := by
          exact Nat.ModEq.pow_totient h_coprime
        refine' ⟨ Nat.totient m, Nat.pos_of_ne_zero _, _, h_euler ⟩;
        · aesop;
        · exact Nat.totient_lt m ( lt_of_le_of_ne ( Nat.pos_of_ne_zero ( by aesop_cat ) ) ( Ne.symm hm_eq_one ) );
      exact h_order;
    -- We want to find $k$ such that $k_0 \mid k$, $k \ge \max(a, b)$, and $k < n$.
    obtain ⟨k, hk⟩ : ∃ k, 0 < k ∧ k < n ∧ k0 ∣ k ∧ k ≥ max a b := by
      use k0 * ( max a b + 1 );
      aesop;
      · -- Since $m > 1$, we have $3^a * 5^b \geq a + 1$ and $3^a * 5^b \geq b + 1$.
        have h_exp : 3^a * 5^b ≥ a + 1 ∧ 3^a * 5^b ≥ b + 1 := by
          have h_exp : ∀ x : ℕ, 3^x ≥ x + 1 := by
            exact fun x => Nat.recOn x ( by norm_num ) fun x ih => by rw [ pow_succ' ] ; linarith [ Nat.one_le_pow x 3 zero_lt_three ] ;
          exact ⟨ le_trans ( h_exp a ) ( Nat.le_of_dvd ( by positivity ) ( dvd_mul_right _ _ ) ), le_trans ( by exact Nat.recOn b ( by norm_num ) fun n ihn => by rw [ pow_succ' ] ; nlinarith [ h_exp n ] ) ( Nat.le_of_dvd ( by positivity ) ( dvd_mul_left _ _ ) ) ⟩;
        cases max_cases a b <;> nlinarith;
      · nlinarith [ Nat.le_max_left a b, Nat.le_max_right a b ];
      · nlinarith [ Nat.le_max_right a b ];
    -- Thus $n = 3^a 5^b m \mid 15^k (135^k - 1) = 2025^k - 15^k$.
    have h_div : 3^a * 5^b * m ∣ 15^k * (135^k - 1) := by
      refine' mul_dvd_mul _ _;
      · rw [ show 15 = 3 * 5 by norm_num, mul_pow ] ; exact mul_dvd_mul ( pow_dvd_pow _ <| by linarith [ le_max_left a b ] ) ( pow_dvd_pow _ <| by linarith [ le_max_right a b ] );
      · rw [ ← Nat.modEq_zero_iff_dvd ] ; simp_all +decide [ ← ZMod.natCast_eq_natCast_iff ];
        rw [ ← Nat.mul_div_cancel' hk.2.2.1, pow_mul ] ; aesop;
    simp_all +decide [ mul_tsub, ← mul_assoc, ← mul_pow ];
    aesop

/-
S contains all positive integers.
-/
theorem S_contains_all_positive_integers (S : Set ℕ) (h : is_valid_S S) :
    ∀ n > 0, n ∈ S := by
      intro n hn; induction' n using Nat.strongRecOn with n ih; rcases n with ( _ | _ | n ) <;> simp_all ( config := { decide := Bool.true } ) ;
      · exact one_in_S S h;
      · -- By the lemma, there exists $k$ such that $0 < k < n + 2$ and $n + 2 \mid 2025^k - 15^k$.
        obtain ⟨k, hk_pos, hk_lt, hk_div⟩ : ∃ k, 0 < k ∧ k < n + 2 ∧ (n + 2 : ℕ) ∣ 2025^k - 15^k := by
          exact exists_divisor_exponent _ ( Nat.succ_lt_succ ( Nat.succ_pos _ ) );
        exact h.2.2 _ ( ih _ ( by linarith ) hk_pos ) _ hk_div
