/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: acb86b8e-0eb7-4d81-9080-8d03b7bbce11
-/

/-
We determine the optimal constants $a = 1/\pi$ and $b = 4/\pi^2$ for the inequality $a x(\pi - x) \le \sin x \le b x(\pi - x)$ on $[0, \pi]$. We prove that these inequalities hold and that the constants are sharp.
-/

import Mathlib

open scoped Classical

set_option maxHeartbeats 0

noncomputable section

/-
The inequality $\frac{1}{\pi} x (\pi - x) \le \sin x$ holds for all $x \in [0, \pi]$.
-/
def a_val : ℝ := 1 / Real.pi
def b_val : ℝ := 4 / Real.pi ^ 2

theorem lower_bound_valid : ∀ x ∈ Set.Icc 0 Real.pi, a_val * x * (Real.pi - x) ≤ Real.sin x := by
  -- Consider the function $f(x) = \sin x - \frac{1}{\pi} x (\pi - x)$.
  set f : ℝ → ℝ := fun x => Real.sin x - (1 / Real.pi) * x * (Real.pi - x);
  -- We'll use the fact that $f(x)$ is differentiable in the interval $[0, \pi]$ and that the derivative is non-negative on $(0, \pi/2)$ and non-positive on $(\pi/2, \pi)$.
  have h_deriv_nonneg : ∀ x ∈ Set.Ioo 0 (Real.pi / 2), 0 ≤ deriv f x := by
    -- Let's calculate the derivative of $f(x)$.
    have h_deriv : ∀ x, deriv f x = Real.cos x - (1 / Real.pi) * (Real.pi - 2 * x) := by
      simp +zetaDelta at *;
      repeat ring <;> norm_num [ Real.differentiableAt_sin, mul_assoc, mul_comm, mul_left_comm ] ;
    aesop;
    rw [ ← Real.sin_pi_div_two_sub ];
    have := Real.mul_le_sin ( by linarith : 0 ≤ Real.pi / 2 - x ) ( by linarith : Real.pi / 2 - x ≤ Real.pi / 2 );
    convert this using 1 ; ring;
  -- Since $f$ is increasing on $(0, \pi/2)$ and decreasing on $(\pi/2, \pi)$, we have $f(x) \geq f(0) = 0$ for all $x \in [0, \pi]$.
  have h_f_nonneg : ∀ x ∈ Set.Icc 0 (Real.pi / 2), 0 ≤ f x := by
    intro x hx; cases hx.1.eq_or_lt <;> aesop;
    have := exists_deriv_eq_slope f h; aesop;
    exact this ( Continuous.continuousOn <| by continuity ) ( Differentiable.differentiableOn <| by ring_nf; norm_num [ Real.differentiable_sin, mul_comm ] ) |> fun ⟨ c, hc₁, hc₂ ⟩ => by nlinarith [ h_deriv_nonneg c hc₁.1 <| hc₁.2.trans_le right, mul_div_cancel₀ ( Real.sin x - Real.pi⁻¹ * x * ( Real.pi - x ) ) h.ne' ] ;
  intro x hx; cases le_total x ( Real.pi / 2 ) <;> aesop;
  · convert h_f_nonneg x left h using 1 ; unfold a_val ; ring;
  · convert h_f_nonneg ( Real.pi - x ) ( by linarith ) ( by linarith ) using 1 <;> norm_num [ a_val ] ; ring

/-
Values of the difference function at key points.
-/
noncomputable def f_diff (x : ℝ) : ℝ := b_val * x * (Real.pi - x) - Real.sin x

lemma f_diff_zero : f_diff 0 = 0 := by
  -- By definition of $f_{\text{diff}}$, we have $f_{\text{diff}}(0) = b_val * 0 * (\pi - 0) - \sin(0)$.
  simp [f_diff, b_val]
lemma f_diff_pi_div_two : f_diff (Real.pi / 2) = 0 := by
  unfold f_diff;
  unfold b_val; norm_num; ring ; norm_num [ mul_div, mul_comm, Real.pi_ne_zero ] ;
lemma f_diff_pi : f_diff Real.pi = 0 := by
  unfold f_diff
  simp [b_val]

/-
The derivative of the difference function.
-/
noncomputable def f_diff_deriv (x : ℝ) : ℝ := b_val * (Real.pi - 2 * x) - Real.cos x

/-
The second derivative of the difference function.
-/
noncomputable def f_diff_deriv2 (x : ℝ) : ℝ := -2 * b_val + Real.sin x

/-
The functions defined are indeed the derivatives.
-/
lemma f_diff_has_deriv : ∀ x, HasDerivAt f_diff (f_diff_deriv x) x := by
  intro x; unfold f_diff f_diff_deriv b_val; convert HasDerivAt.sub ( HasDerivAt.mul ( hasDerivAt_id x |> HasDerivAt.const_mul _ ) ( hasDerivAt_id x |> HasDerivAt.const_sub _ ) ) ( Real.hasDerivAt_sin x ) using 1 ; ring;
  rfl
lemma f_diff_deriv_has_deriv : ∀ x, HasDerivAt f_diff_deriv (f_diff_deriv2 x) x := by
  unfold f_diff_deriv f_diff_deriv2;
  exact fun x => by convert HasDerivAt.sub ( HasDerivAt.const_mul _ ( HasDerivAt.const_sub _ ( HasDerivAt.const_mul _ ( hasDerivAt_id x ) ) ) ) ( Real.hasDerivAt_cos x ) using 1 ; ring;

/-
The roots of the second derivative.
-/
noncomputable def x1 : ℝ := Real.arcsin (2 * b_val)
noncomputable def x2 : ℝ := Real.pi - x1

/-
Positivity of b.
-/
lemma b_val_pos : 0 < b_val := by
  exact div_pos ( by norm_num ) ( pow_pos Real.pi_pos 2 )

/-
Bound on 2b.
-/
lemma two_b_val_lt_one : 2 * b_val < 1 := by
  exact by rw [ show b_val = 4 / Real.pi ^ 2 by rfl ] ; rw [ mul_div, div_lt_iff₀ ] <;> nlinarith only [ Real.pi_gt_three ] ;

/-
Positivity of x1.
-/
lemma x1_pos : 0 < x1 := by
  exact Real.arcsin_pos.mpr ( by rw [ b_val ] ; positivity )

/-
Upper bound on x1.
-/
lemma x1_lt_pi_div_two : x1 < Real.pi / 2 := by
  -- Since $2b < 1$, we have $\arcsin(2b) < \arcsin(1) = \frac{\pi}{2}$.
  have h_arcsin_lt_pi_div_2 : Real.arcsin (2 * b_val) < Real.arcsin 1 := by
    norm_num [ b_val ];
    rw [ mul_div, div_lt_iff₀ ] <;> nlinarith [ Real.pi_gt_three ];
  rwa [ Real.arcsin_one ] at h_arcsin_lt_pi_div_2

/-
Lower bound on x2.
-/
lemma x2_gt_pi_div_two : x2 > Real.pi / 2 := by
  unfold x2; linarith [ Real.pi_pos, x1_lt_pi_div_two ] ;

/-
Sign of the second derivative on the intervals.
-/
lemma f_diff_deriv2_neg_of_lt_x1 : ∀ x ∈ Set.Ioo 0 x1, f_diff_deriv2 x < 0 := by
  unfold f_diff_deriv2;
  intro x hx;
  -- Since $x \in (0, x_1)$, we have $\sin x < \sin x_1 = 2b_val$.
  have h_sin_lt : Real.sin x < Real.sin (Real.arcsin (2 * b_val)) := by
    rw [ ← Real.cos_pi_div_two_sub, ← Real.cos_pi_div_two_sub ] ; refine' Real.cos_lt_cos_of_nonneg_of_le_pi _ _ _ <;> aesop;
    · linarith [ Real.arcsin_le_pi_div_two ( 2 * b_val ) ];
    · linarith [ Real.pi_pos ];
  rw [ Real.sin_arcsin ] at h_sin_lt <;> nlinarith [ Real.pi_gt_three, b_val_pos, two_b_val_lt_one, mul_div_cancel₀ 4 ( ne_of_gt ( pow_pos Real.pi_pos 2 ) ) ]
lemma f_diff_deriv2_pos_of_x1_lt_x2 : ∀ x ∈ Set.Ioo x1 x2, f_diff_deriv2 x > 0 := by
  unfold f_diff_deriv2; aesop;
  by_cases hx : x ≤ Real.pi / 2;
  · -- Since $x \in (x_1, \pi/2]$, we have $\sin x > \sin x_1 = 2b$.
    have h_sin_x_gt_sin_x1 : Real.sin x > Real.sin x1 := by
      rw [ ← Real.cos_pi_div_two_sub, ← Real.cos_pi_div_two_sub ] ; exact Real.cos_lt_cos_of_nonneg_of_le_pi ( by linarith [ Real.arcsin_nonneg.2 ( show 0 ≤ 2 * b_val by exact mul_nonneg zero_le_two ( show 0 ≤ b_val by exact div_nonneg zero_le_four ( sq_nonneg _ ) ) ), Real.arcsin_le_pi_div_two ( 2 * b_val ), show x1 ≥ 0 by exact Real.arcsin_nonneg.2 ( show 0 ≤ 2 * b_val by exact mul_nonneg zero_le_two ( show 0 ≤ b_val by exact div_nonneg zero_le_four ( sq_nonneg _ ) ) ) ] ) ( by linarith [ Real.arcsin_nonneg.2 ( show 0 ≤ 2 * b_val by exact mul_nonneg zero_le_two ( show 0 ≤ b_val by exact div_nonneg zero_le_four ( sq_nonneg _ ) ) ), Real.arcsin_le_pi_div_two ( 2 * b_val ), show x1 ≥ 0 by exact Real.arcsin_nonneg.2 ( show 0 ≤ 2 * b_val by exact mul_nonneg zero_le_two ( show 0 ≤ b_val by exact div_nonneg zero_le_four ( sq_nonneg _ ) ) ) ] ) ( by linarith );
    unfold x1 at * ; aesop;
    rwa [ Real.sin_arcsin ] at h_sin_x_gt_sin_x1 <;> nlinarith [ two_b_val_lt_one, b_val_pos ];
  · -- Since $x > \pi/2$, we have $\sin x > \sin x_2$.
    have h_sin_gt_sin_x2 : Real.sin x > Real.sin x2 := by
      rw [ ← Real.cos_sub_pi_div_two, ← Real.cos_sub_pi_div_two ] ; exact Real.cos_lt_cos_of_nonneg_of_le_pi ( by linarith [ Real.pi_pos, show x2 ≤ Real.pi from by unfold x2; linarith [ Real.pi_pos, show x1 ≥ 0 from by exact Real.arcsin_nonneg.2 <| by exact mul_nonneg zero_le_two <| by exact div_nonneg zero_le_four <| sq_nonneg _ ] ] ) ( by linarith [ Real.pi_pos, show x2 ≤ Real.pi from by unfold x2; linarith [ Real.pi_pos, show x1 ≥ 0 from by exact Real.arcsin_nonneg.2 <| by exact mul_nonneg zero_le_two <| by exact div_nonneg zero_le_four <| sq_nonneg _ ] ] ) ( by linarith );
    rw [ show x2 = Real.pi - x1 by rfl, Real.sin_pi_sub ] at h_sin_gt_sin_x2 ; aesop;
    rw [ show x1 = Real.arcsin ( 2 * b_val ) by rfl, Real.sin_arcsin ] at h_sin_gt_sin_x2 <;> nlinarith [ Real.pi_gt_three, b_val_pos, two_b_val_lt_one ]
lemma f_diff_deriv2_neg_of_gt_x2 : ∀ x ∈ Set.Ioo x2 Real.pi, f_diff_deriv2 x < 0 := by
  -- For $x \in (x_2, \pi)$, $\sin x < 2b$ because sine is decreasing on $[0, \pi]$.
  intros x hx
  have h_sin_lt : Real.sin x < 2 * b_val := by
    -- Since $x \in (x_2, \pi)$, we have $\sin x < \sin x_2$ because $\sin$ is decreasing on $[\pi/2, \pi]$.
    have h_sin_decreasing : Real.sin x < Real.sin x2 := by
      rw [ ← Real.cos_sub_pi_div_two, ← Real.cos_sub_pi_div_two ] ; refine' Real.cos_lt_cos_of_nonneg_of_le_pi _ _ _ <;> linarith [ hx.1, hx.2, Real.arcsin_nonneg.mpr ( show 0 ≤ 2 * ( 4 / Real.pi ^ 2 ) by positivity ), Real.arcsin_le_pi_div_two ( 2 * ( 4 / Real.pi ^ 2 ) ), show x2 = Real.pi - Real.arcsin ( 2 * ( 4 / Real.pi ^ 2 ) ) from rfl ] ;
    unfold b_val x2 at * ; aesop;
    rw [ show x1 = Real.arcsin ( 2 * ( 4 / Real.pi ^ 2 ) ) by rfl, Real.sin_arcsin ] at h_sin_decreasing <;> nlinarith [ Real.pi_gt_three, mul_div_cancel₀ ( 4 : ℝ ) ( ne_of_gt <| sq_pos_of_pos Real.pi_pos ) ];
  exact show -2 * b_val + Real.sin x < 0 by linarith!;

/-
Signs of the derivative at key points.
-/
lemma f_diff_deriv_zero_pos : f_diff_deriv 0 > 0 := by
  norm_num [ f_diff_deriv, b_val ];
  rw [ div_mul_eq_mul_div, one_lt_div ] <;> nlinarith [ Real.pi_gt_three, show Real.pi < 4 by pi_upper_bound [ ] ]
lemma f_diff_deriv_pi_neg : f_diff_deriv Real.pi < 0 := by
  unfold f_diff_deriv;
  rw [ show b_val = 4 / Real.pi ^ 2 from rfl ] ; ring_nf ; norm_num [ Real.pi_pos.ne' ];
  field_simp;
  pi_upper_bound [ ]
lemma f_diff_deriv_pi_div_two : f_diff_deriv (Real.pi / 2) = 0 := by
  unfold f_diff_deriv ; norm_num [ b_val ] ; ring;

/-
Signs of the derivative at the critical points of the second derivative.
-/
lemma f_diff_deriv_x1_neg : f_diff_deriv x1 < 0 := by
  -- Since $f'(x)$ is increasing on $(x_1, x_2)$ and $x_1 < \pi/2$, we have $f'(x_1) < f'(\pi/2) = 0$.
  have h_inc : StrictMonoOn f_diff_deriv (Set.Icc x1 x2) := by
    have h_deriv_inc : ∀ x ∈ Set.Ioo x1 x2, 0 < f_diff_deriv2 x := by
      exact?;
    intro x hx y hy hxy; have := exists_deriv_eq_slope f_diff_deriv hxy; aesop;
    contrapose! this;
    exact ⟨ Continuous.continuousOn <| by exact ( show Continuous f_diff_deriv from by exact ( by exact ( by exact ( by exact ( by exact by rw [ show f_diff_deriv = _ from funext fun _ => rfl ] ; exact by { exact Continuous.sub ( continuous_const.mul ( continuous_const.sub ( continuous_const.mul continuous_id' ) ) ) ( Real.continuous_cos ) } ) ) ) ) ), fun z hz => DifferentiableAt.differentiableWithinAt <| by exact ( by exact ( by exact ( by exact ( by exact by rw [ show f_diff_deriv = _ from funext fun _ => rfl ] ; exact by { exact DifferentiableAt.sub ( DifferentiableAt.mul ( differentiableAt_const _ ) ( differentiableAt_const _ |> DifferentiableAt.sub <| differentiableAt_id.const_mul _ ) ) ( Real.differentiableAt_cos ) } ) ) ) ), fun z hz => by rw [ ne_eq, eq_div_iff ] <;> nlinarith [ h_deriv_inc z ( by linarith ) ( by linarith ), ( f_diff_deriv_has_deriv z |> HasDerivAt.deriv ) ] ⟩;
  have h_lt : x1 < Real.pi / 2 := by
    exact?;
  simpa [ h_lt.le ] using h_inc ⟨ by linarith [ Real.pi_pos, x1_pos ], by linarith [ Real.pi_pos, x1_lt_pi_div_two, x2_gt_pi_div_two ] ⟩ ⟨ by linarith [ Real.pi_pos, x1_pos ], by linarith [ Real.pi_pos, x1_lt_pi_div_two, x2_gt_pi_div_two ] ⟩ h_lt |> fun h => h.trans_le <| by simpa [ h_lt.le ] using f_diff_deriv_pi_div_two.le;
lemma f_diff_deriv_x2_pos : f_diff_deriv x2 > 0 := by
  -- Since $x_2 > \pi/2$, and $f'(\pi/2) = 0$, it follows that $f'(x_2) > 0$.
  have h_deriv_pos : f_diff_deriv x2 > f_diff_deriv (Real.pi / 2) := by
    -- Since $x_2 > \pi/2$, we have $f''(x) > 0$ for $x \in (\pi/2, x_2)$.
    have h_second_deriv_pos : ∀ x ∈ Set.Ioo (Real.pi / 2) x2, f_diff_deriv2 x > 0 := by
      exact fun x hx => f_diff_deriv2_pos_of_x1_lt_x2 x ⟨ by linarith [ hx.1, x1_lt_pi_div_two ], hx.2 ⟩;
    -- Apply the mean value theorem to the interval $(\pi/2, x2)$.
    obtain ⟨c, hc⟩ : ∃ c ∈ Set.Ioo (Real.pi / 2) x2, deriv f_diff_deriv c = (f_diff_deriv x2 - f_diff_deriv (Real.pi / 2)) / (x2 - Real.pi / 2) := by
      apply_rules [ exists_deriv_eq_slope ];
      · exact?;
      · exact Continuous.continuousOn ( by rw [ show f_diff_deriv = fun x => b_val * ( Real.pi - 2 * x ) - Real.cos x from funext fun _ => rfl ] ; continuity );
      · exact fun x hx => DifferentiableAt.differentiableWithinAt ( by exact HasDerivAt.differentiableAt ( f_diff_deriv_has_deriv x ) );
    have := h_second_deriv_pos c hc.1; rw [ f_diff_deriv_has_deriv c |> HasDerivAt.deriv ] at *; rw [ eq_div_iff ] at * <;> nlinarith [ hc.1.1, hc.1.2 ] ;
  linarith [ f_diff_deriv_pi_div_two ]

/-
Existence of a root $r$ such that $f'$ is positive before and negative after (up to $\pi/2$).
-/
lemma f_diff_deriv_pos_of_lt_root : ∃ r ∈ Set.Ioo 0 x1, (∀ x ∈ Set.Ioo 0 r, f_diff_deriv x > 0) ∧ (∀ x ∈ Set.Ioo r (Real.pi / 2), f_diff_deriv x < 0) := by
  -- By the Intermediate Value Theorem, since $f'(0) > 0$ and $f'(x_1) < 0$, there exists $r \in (0, x_1)$ such that $f'(r) = 0$.
  obtain ⟨r, hr⟩ : ∃ r ∈ Set.Ioo 0 x1, f_diff_deriv r = 0 := by
    apply_rules [ intermediate_value_Ioo' ] <;> norm_num;
    · exact le_of_lt ( x1_pos );
    · exact Continuous.continuousOn ( by rw [ show f_diff_deriv = fun x => b_val * ( Real.pi - 2 * x ) - Real.cos x from funext fun _ => rfl ] ; continuity );
    · exact ⟨ f_diff_deriv_x1_neg, f_diff_deriv_zero_pos ⟩;
  refine' ⟨ r, hr.1, _, _ ⟩ <;> aesop;
  · -- Since $f''(x) < 0$ on $(0, x_1)$, we have $f'(x)$ is strictly decreasing on $[0, x_1]$.
    have h_deriv_decreasing : StrictAntiOn f_diff_deriv (Set.Icc 0 x1) := by
      -- Since $f''(x) < 0$ on $(0, x_1)$, we have $f'(x)$ is strictly decreasing on $[0, x_1]$ by the Mean Value Theorem.
      intros x hx y hy hxy
      have h_mean_value : ∃ c ∈ Set.Ioo x y, deriv f_diff_deriv c = (f_diff_deriv y - f_diff_deriv x) / (y - x) := by
        apply_rules [ exists_deriv_eq_slope ];
        · exact Continuous.continuousOn ( by rw [ show f_diff_deriv = fun x => b_val * ( Real.pi - 2 * x ) - Real.cos x from funext fun x => rfl ] ; continuity );
        · exact fun z hz => DifferentiableAt.differentiableWithinAt ( by exact HasDerivAt.differentiableAt ( f_diff_deriv_has_deriv z ) );
      aesop;
      -- Since $f''(x) < 0$ on $(0, x_1)$, we have $f'(x)$ is strictly decreasing on $[0, x_1]$ by the Mean Value Theorem and the fact that $f''(x)$ is negative.
      have h_deriv_neg : ∀ x ∈ Set.Ioo 0 x1, deriv f_diff_deriv x < 0 := by
        intros x hx; rw [ show deriv f_diff_deriv x = f_diff_deriv2 x from HasDerivAt.deriv ( f_diff_deriv_has_deriv x ) ] ; exact f_diff_deriv2_neg_of_lt_x1 x hx;
      have := h_deriv_neg w ⟨ by linarith, by linarith ⟩ ; rw [ right_5, div_lt_iff₀ ] at this <;> linarith;
    linarith [ h_deriv_decreasing ⟨ by linarith, by linarith ⟩ ⟨ by linarith, by linarith ⟩ right_1 ];
  · -- Since $f'(x)$ is strictly decreasing on $[0, x_1]$, we have $f'(x) < f'(r)$ for $x \in (r, x_1]$.
    have h_deriv_decreasing : ∀ x ∈ Set.Ioo r x1, f_diff_deriv x < f_diff_deriv r := by
      intros x hx
      have h_deriv_decreasing : ∀ x ∈ Set.Ioo 0 x1, deriv f_diff_deriv x < 0 := by
        intros x hx; rw [ show deriv f_diff_deriv x = f_diff_deriv2 x from HasDerivAt.deriv ( f_diff_deriv_has_deriv x ) ] ; exact f_diff_deriv2_neg_of_lt_x1 x hx;
      have := exists_deriv_eq_slope f_diff_deriv hx.1; aesop;
      exact this ( continuousOn_of_forall_continuousAt fun y hy => HasDerivAt.continuousAt <| f_diff_deriv_has_deriv y ) ( fun y hy => DifferentiableAt.differentiableWithinAt <| f_diff_deriv_has_deriv y |> HasDerivAt.differentiableAt ) |> fun ⟨ c, hc₁, hc₂ ⟩ => by nlinarith [ h_deriv_decreasing c ( by linarith ) ( by linarith ), mul_div_cancel₀ ( f_diff_deriv x ) ( by linarith : ( x - r ) ≠ 0 ) ] ;
    -- Since $f'(x)$ is strictly increasing on $(x_1, \pi/2)$, we have $f'(x) < f'(\pi/2)$ for $x \in (x_1, \pi/2)$.
    have h_deriv_increasing : ∀ x ∈ Set.Ioo x1 (Real.pi / 2), f_diff_deriv x < f_diff_deriv (Real.pi / 2) := by
      intros x hx
      have h_deriv_pos : ∀ y ∈ Set.Ioo x1 (Real.pi / 2), 0 < f_diff_deriv2 y := by
        aesop;
        exact f_diff_deriv2_pos_of_x1_lt_x2 y ⟨ by linarith, by linarith [ Real.pi_pos, show x2 = Real.pi - x1 from rfl, show x2 > Real.pi / 2 from by linarith [ Real.pi_pos, show x2 = Real.pi - x1 from rfl ] ] ⟩;
      have := exists_deriv_eq_slope f_diff_deriv hx.2; aesop;
      contrapose! this;
      exact ⟨ Continuous.continuousOn <| by exact continuous_iff_continuousAt.mpr fun y => HasDerivAt.continuousAt <| f_diff_deriv_has_deriv y, fun y hy => DifferentiableAt.differentiableWithinAt <| by exact HasDerivAt.differentiableAt <| f_diff_deriv_has_deriv y, fun y hy => by rw [ ne_eq, eq_div_iff ] <;> nlinarith [ h_deriv_pos y ( by linarith ) ( by linarith ), show deriv f_diff_deriv y = f_diff_deriv2 y from HasDerivAt.deriv <| f_diff_deriv_has_deriv y ] ⟩;
    cases lt_trichotomy x x1 <;> aesop;
    · -- Since $f'(x)$ is continuous, we have $f'(x_1) = \lim_{x \to x_1^-} f'(x)$.
      have h_deriv_cont : Filter.Tendsto f_diff_deriv (nhdsWithin x1 (Set.Iio x1)) (nhds (f_diff_deriv x1)) := by
        exact Continuous.continuousWithinAt ( by exact by rw [ show f_diff_deriv = fun x => b_val * ( Real.pi - 2 * x ) - Real.cos x from funext fun x => rfl ] ; continuity );
      exact lt_of_le_of_ne ( le_of_tendsto h_deriv_cont <| Filter.eventually_of_mem ( Ioo_mem_nhdsLT left_1 ) fun x hx => le_of_lt <| h_deriv_decreasing x hx.1 hx.2 ) <| by linarith [ f_diff_deriv_x1_neg ] ;
    · linarith [ h_deriv_increasing x h_2 right_1, show f_diff_deriv ( Real.pi / 2 ) = 0 from by unfold f_diff_deriv; norm_num [ b_val ] ; ring ]

/-
Non-negativity of the difference function on the left half.
-/
lemma f_diff_nonneg_on_left : ∀ x ∈ Set.Icc 0 (Real.pi / 2), f_diff x ≥ 0 := by
  -- Use the existence of $r$ such that $f'$ is positive on $(0, r)$ and negative on $(r, \pi/2)$.
  obtain ⟨r, hr₀, hr₁, hr₂⟩ : ∃ r ∈ Set.Ioo 0 x1, (∀ x ∈ Set.Ioo 0 r, f_diff_deriv x > 0) ∧ (∀ x ∈ Set.Ioo r (Real.pi / 2), f_diff_deriv x < 0) := f_diff_deriv_pos_of_lt_root;
  -- On $[0, r]$, $f$ increases from 0, so $f \ge 0$.
  have h_inc : ∀ x ∈ Set.Icc 0 r, f_diff x ≥ 0 := by
    -- Apply the mean value theorem to the interval $[0, x]$ for $x \in (0, r]$.
    have h_mvt : ∀ x ∈ Set.Ioc 0 r, ∃ c ∈ Set.Ioo 0 x, deriv f_diff c = (f_diff x - f_diff 0) / (x - 0) := by
      intro x hx; apply_rules [ exists_deriv_eq_slope _, hx.1, hx.2 ] ; aesop;
      · exact Continuous.continuousOn ( by unfold f_diff; continuity );
      · exact fun y hy => DifferentiableAt.differentiableWithinAt ( by exact HasDerivAt.differentiableAt ( f_diff_has_deriv y ) );
    intro x hx; cases hx.1.eq_or_lt <;> aesop;
    · unfold f_diff; norm_num;
    · obtain ⟨ c, ⟨ hc₁, hc₂ ⟩, hc ⟩ := h_mvt x h right_1 ; have := hr₁ c hc₁ ( by linarith ) ; rw [ show deriv f_diff c = f_diff_deriv c from HasDerivAt.deriv ( f_diff_has_deriv c ) ] at hc ; rw [ eq_div_iff ] at hc <;> nlinarith [ f_diff_zero ];
  -- On $[r, \pi/2]$, $f$ decreases to 0, so $f \ge 0$.
  have h_dec : ∀ x ∈ Set.Icc r (Real.pi / 2), f_diff x ≥ f_diff (Real.pi / 2) := by
    intro x hx; cases hx.2.eq_or_lt <;> aesop;
    -- Apply the Mean Value Theorem to the interval $[x, \pi/2]$.
    obtain ⟨c, hc⟩ : ∃ c ∈ Set.Ioo x (Real.pi / 2), deriv f_diff c = (f_diff (Real.pi / 2) - f_diff x) / ((Real.pi / 2) - x) := by
      apply_rules [ exists_deriv_eq_slope ];
      · exact Continuous.continuousOn ( by unfold f_diff; continuity );
      · exact fun x hx => DifferentiableAt.differentiableWithinAt ( by exact HasDerivAt.differentiableAt ( f_diff_has_deriv x ) );
    rw [ show deriv f_diff c = f_diff_deriv c from HasDerivAt.deriv ( f_diff_has_deriv c ) ] at hc ; rw [ eq_div_iff ] at hc <;> nlinarith [ hc.1.1, hc.1.2, hr₂ c ( by linarith [ hc.1.1, hc.1.2 ] ) ( by linarith [ hc.1.1, hc.1.2 ] ) ];
  exact fun x hx => if hx' : x ≤ r then h_inc x ⟨ hx.1, hx' ⟩ else h_dec x ⟨ le_of_not_ge hx', hx.2 ⟩ |> le_trans ( by norm_num [ show f_diff ( Real.pi / 2 ) = 0 from f_diff_pi_div_two ] ) ;

/-
Symmetry of the difference function.
-/
lemma f_diff_symm : ∀ x, f_diff (Real.pi - x) = f_diff x := by
  intro x; unfold f_diff; norm_num; ring;

/-
Non-negativity of the difference function on the right half.
-/
lemma f_diff_nonneg_on_right : ∀ x ∈ Set.Icc (Real.pi / 2) Real.pi, f_diff x ≥ 0 := by
  intro x hx_left_right; rw [ show f_diff x = f_diff ( Real.pi - x ) by exact? ] ; aesop;
  exact f_diff_nonneg_on_left _ ⟨ by linarith, by linarith ⟩

/-
The upper bound inequality holds.
-/
theorem upper_bound_valid : ∀ x ∈ Set.Icc 0 Real.pi, Real.sin x ≤ b_val * x * (Real.pi - x) := by
  -- By combining the results for the left and right halves, we can conclude that the inequality holds on the entire interval.
  have h_combined : ∀ x ∈ Set.Icc 0 Real.pi, f_diff x ≥ 0 := by
    exact fun x hx => if hx' : x ≤ Real.pi / 2 then f_diff_nonneg_on_left x ⟨ hx.1, hx' ⟩ else f_diff_nonneg_on_right x ⟨ by linarith [ hx.1, hx.2 ], hx.2 ⟩;
  exact fun x hx => le_of_sub_nonneg ( by simpa only [ f_diff ] using h_combined x hx )

/-
Optimality of the upper bound constant b.
-/
theorem b_optimal : ∀ b' : ℝ, (∀ x ∈ Set.Icc 0 Real.pi, Real.sin x ≤ b' * x * (Real.pi - x)) → b_val ≤ b' := by
  intro b' hb' ; have := hb' ( Real.pi / 2 ) ⟨ by linarith [ Real.pi_pos ], by linarith [ Real.pi_pos ] ⟩ ; norm_num at this ⊢ ; aesop;
  unfold b_val; rw [ div_le_iff₀ ] <;> nlinarith [ Real.pi_gt_three ] ;

/-
Optimality of the lower bound constant a.
-/
theorem a_optimal : ∀ a' : ℝ, (∀ x ∈ Set.Icc 0 Real.pi, a' * x * (Real.pi - x) ≤ Real.sin x) → a' ≤ a_val := by
  simp +zetaDelta at *;
  intro a' ha'
  have h_lim : Filter.Tendsto (fun x => Real.sin x / (x * (Real.pi - x))) (nhdsWithin 0 (Set.Ioi 0)) (nhds (1 / Real.pi)) := by
    -- We can use the fact that $\sin x / x \to 1$ as $x \to 0$.
    have h_sin_x_over_x : Filter.Tendsto (fun x => Real.sin x / x) (nhdsWithin 0 (Set.Ioi 0)) (nhds 1) := by
      simpa [ div_eq_inv_mul ] using Real.hasDerivAt_sin 0 |> HasDerivAt.tendsto_slope_zero_right;
    simpa [ div_mul_eq_div_div ] using h_sin_x_over_x.div ( Continuous.continuousWithinAt ( show Continuous fun x : ℝ => Real.pi - x from continuous_const.sub continuous_id' ) ) ( by linarith [ Real.pi_pos ] );
  -- By the properties of limits, if $a' * x * (π - x) ≤ Real.sin x$ for all $x ∈ [0, π]$, then $\lim_{x \to 0} \frac{\sin x}{x(\pi - x)} ≥ a'$.
  have h_lim_ge : ∀ᶠ x in nhdsWithin 0 (Set.Ioi 0), (Real.sin x) / (x * (Real.pi - x)) ≥ a' := by
    filter_upwards [ Ioo_mem_nhdsGT_of_mem ⟨ le_rfl, Real.pi_div_two_pos ⟩ ] with x hx using by rw [ ge_iff_le ] ; rw [ le_div_iff₀ ] <;> nlinarith [ ha' x hx.1.le ( by linarith [ hx.2, Real.pi_pos ] ), hx.1, hx.2, Real.pi_gt_three ] ;
  exact le_of_tendsto_of_tendsto tendsto_const_nhds h_lim ( Filter.eventually_of_mem h_lim_ge fun x hx => hx ) |> le_trans <| by norm_num [ a_val ] ;
